### ISSUE TITLE
fastify 1.3.0 does not support?

### ISSUE THREAD

**Issue by caryhgq** [coopnd/fastify-apollo#15]
/Users/xxx/NodeJS/fastify-graphql/node_modules/fastify-plugin/index.js:24
      throw new Error(`fastify-plugin - expected '${version}' fastify version, '${fastifyVersion}' is installed`)
      ^

Error: fastify-plugin - expected '^0.3x' fastify version, '1.3.0' is installed
    at plugin (/Users/xxx/NodeJS/fastify-graphql/node_modules/fastify-plugin/index.js:24:13)
    at fp (/Users/xxx/NodeJS/fastify-graphql/node_modules/fastify-apollo/index.js:6:28)
    at Object.<anonymous> (/Users/xxx/NodeJS/fastify-graphql/node_modules/fastify-apollo/index.js:26:29)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

**Comment by Extarys** [comment]
Same error here :(
